import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class Data {
	//Datsets as a multidimensional array
	static String[][] DIAGNOSIS = {
			{"SYMPTOM", "DIAGNOSIS"},
			{"polyuria", "diabetes"},
			{"fever", "dementia"},
			{"polydypsia", "diabetes"},
			{"fall", "dementia"},
			{"shortness of breath", "diabetes"},
			{"unresponsiveness", "dementia"},
			{"pain chest", "diabetes"},
			{"lethargy", "dementia"},
			{"asthenia", "diabetes"},
			{"agitation", "dementia"},
			{"nausea", "diabetes"},
			{"ecchymosis", "dementia"},
			{"orthopnea", "diabetes"},
			{"dementia", "syncop"},
			{"rale", "diabetes"},
			{"rale", "dementia"},
			{"sweat sweating increased", "diabetes"},
			{"unconscious state", "dementia"},
			{"unresponsiveness", "diabetes"},
			{"cough", "dementia"},
			{"mental status changes", "diabetes"},
			{"bedridden bedridden", "dementia"},
			{"vertigo", "diabetes"},
			{"pain", "dementia"},
			{"vomiting", "diabetes"},
			{"facial paresis", "dementia"},
			{"labored breathing", "diabetes"},
			{"abdominal tenderness", "dementia"},
			{"rhonchus", "dementia"},
			{"unsteady gait", "dementia"},
			{"hallucinations auditory", "dementia"},
			{"wheezing", "asthma"},
			{"cough", "asthma"},
			{"shortness of breath", "asthma"},
			{"chest tightness", "asthma"},
			{"productive cough", "asthma"},
			{"symptom aggravating factors", "asthma"},
			{"distress respiratory", "asthma"},
			{"fever", "infection"},
			{"erythema", "infection"},
			{"decreased translucency", "infection"},
			{"hepatosplenomegaly", "infection"},
			{"chill", "infection"},
			{"pruritus", "infection"},
			{"diarrhea", "infection"},
			{"abscess bacterial", "infection"},
			{"swelling", "infection"},
			{"pain", "infection"},
			{"apyrexial", "infection"},
			{"cough", "infection"}
	};

	static String[][] Diagnosis = {
			{"symptom", "symptom", "symptom", "diagnosis"},
			{"shortness of breath", "dizziness", "asthenia", "hypertention disease"},
			{"shortness of breath", "asthenia", "dizziness", "hypertention disease"},
			{"dizziness", "shortness of breath", "asthenia", "hypertention disease"},
			{"dizziness", "asthenia", "shortness of breath", "hypertention disease"},
			{"asthenia", "shortness of breath", "dizziness", "hypertention disease"},
			{"asthenia", "dizziness", "shortness of breath", "hypertention disease"},
			{"polyuria", "polydysia", "shortness of breath", "diabetes"},
			{"polyuria", "shortness of breath", "polydysia", "diabetes"},
			{"shortness of breath", "polyuria", "polydysia", "diabetes"},
			{"shortness of breath", "polydysia", "polyuria", "diabetes"},
			{"polydysia", "shortness of breath", "polyuria", "diabetes"},
			{"polydysia", "polyuria", "shortness of breath", "diabetes"},
			{"feeling suicidal", "feeling hopeless", "unable to concentrate", "depressive disorder"},
			{"feeling suicidal", "unable to concentrate", "feeling hopeless", "depressive disorder"},
			{"feeling hopeless", "feeling suicidal", "unable to concentrate", "depressive disorder"},
			{"feeling hopeless", "unable to concentrate", "feeling suicidal", "depressive disorder"},
			{"unable to concentrate", "feeling suicidal", "feeling hopeless", "depressive disorder"},
			{"unable to concentrate", "feeling hopeless", "feeling suicidal", "depressive disorder"},
			{"smoking", "dyspnoea", "bronchitis", "lung cancer"},
			{"smoking", "bronchitis", "dyspnoea", "lung cancer"},
			{"dyspnoea", "smoking", "bronchitis", "lung cancer"},
			{"dyspnoea", "bronchitis", "smoking", "lung cancer"},
			{"bronchitis", "smoking", "dyspnoea", "lung cancer"},
			{"bronchitis", "dyspnoea", "smoking", "lung cancer"},
			{"pain chest", "shortness of breath", "hypokinesia", "coronary heart disease"},
			{"pain chest", "hypokinesia", "shortness of breath", "coronary heart disease"},
			{"shortness of breath", "pain chest", "hypokinesia", "coronary heart disease"},
			{"shortness of breath", "hypokinesia", "pain chest", "coronary heart disease"},
			{"hypokinesia", "pain chest", "shortness of breath", "coronary heart disease"},
			{"hypokinesia", "shortness of breath", "pain chest", "coronary heart disease"},
			{"cough", "fever", "rhonchus", "pneumonia"},
			{"cough", "rhonchus", "fever", "pneumonia"},
			{"fever", "cough", "rhonchus", "pneumonia"},
			{"fever", "rhonchus", "cough", "pneumonia"},
			{"rhonchus", "cough", "fever", "pneumonia"},
			{"rhonchus", "fever", "cough", "pneumonia"},
			{"shortness of breath", "dyspnea", "wheezing", "failure heart congestive"},
			{"shortness of breath", "wheezing", "dyspnea", "failure heart congestive"},
			{"dyspnea", "shortness of breath", "wheezing", "failure heart congestive"},
			{"dyspnea", "wheezing", "shortness of breath", "failure heart congestive"},
			{"wheezing", "shortness of breath", "dyspnea", "failure heart congestive"},
			{"wheezing", "dyspnea", "shortness of breath", "failure heart congestive"},
			{"dysarthria", "asthenia", "speech slurred", "accident cerebrovascular"},
			{"dysarthria", "speech slurred", "asthenia", "accident cerebrovascular"},
			{"asthenia", "dysarthria", "speech slurred", "accident cerebrovascular"},
			{"asthenia", "speech slurred", "dysarthria", "accident cerebrovascular"},
			{"speech slurred", "dysarthria", "asthenia", "accident cerebrovascular"},
			{"speech slurred", "asthenia", "dysarthria", "accident cerebrovascular"},
			{"wheezing", "cough", "shortness of breath", "asthma"},
			{"wheezing", "shortness of breath", "cough", "asthma"},
			{"cough", "wheezing", "shortness of breath", "asthma"},
			{"cough", "shortness of breath", "wheezing", "asthma"},
			{"shortness of breath", "wheezing", "cough", "asthma"},
			{"shortness of breath", "cough", "wheezing", "asthma"},
			{"pain chest", "chest tightness", "rale", "myocardial infarction"},
			{"pain chest", "rale", "chest tightness", "myocardial infarction"},
			{"chest tightness", "pain chest", "rale", "myocardial infarction"},
			{"chest tightness", "rale", "pain chest", "myocardial infarction"},
			{"rale", "pain chest", "chest tightness", "myocardial infarction"},
			{"rale", "chest tightness", "pain chest", "myocardial infarction"},
			{"pain", "pain chest", "sweat sweating increased", "hypercholesterolemia"},
			{"pain", "sweat sweating increased", "pain chest", "hypercholesterolemia"},
			{"pain chest", "pain", "sweat sweating increased", "hypercholesterolemia"},
			{"pain chest", "sweat sweating increased", "pain", "hypercholesterolemia"},
			{"sweat sweating increased", "pain", "pain chest", "hypercholesterolemia"},
			{"sweat sweating increased", "pain chest", "pain", "hypercholesterolemia"},
			{"fever", "swelling", "chill", "infection"},
			{"fever", "chill", "swelling", "infection"},
			{"swelling", "fever", "chill", "infection"},
			{"swelling", "chill", "fever", "infection"},
			{"chill", "fever", "swelling", "infection"},
			{"chill", "swelling", "fever", "infection"},
			{"fever", "difficulty passing urine", "hyponatremia", "infection urinary tract"},
			{"fever", "hyponatremia", "difficulty passing urine", "infection urinary tract"},
			{"difficulty passing urine", "fever", "hyponatremia", "infection urinary tract"},
			{"difficulty passing urine", "hyponatremia", "fever", "infection urinary tract"},
			{"hyponatremia", "fever", "difficulty passing urine", "infection urinary tract"},
			{"hyponatremia", "difficulty passing urine", "fever", "infection urinary tract"},
			{"chill", "guaiac positive", "monoclonal", "anemia"},
			{"chill", "monoclonal", "guaiac positive", "anemia"},
			{"guaiac positive", "chill", "monoclonal", "anemia"},
			{"guaiac positive", "monoclonal", "chill", "anemia"},
			{"monoclonal", "chill", "guaiac positive", "anemia"},
			{"monoclonal", "guaiac positive", "chill", "anemia"},
			{"wheezing", "distress respiratory", "sputum purulent", "chronic obstructive airway disease"},
			{"wheezing", "sputum purulent", "distress respiratory", "chronic obstructive airway disease"},
			{"distress respiratory", "wheezing", "sputum purulent", "chronic obstructive airway disease"},
			{"distress respiratory", "sputum purulent", "wheezing", "chronic obstructive airway disease"},
			{"sputum purulent", "wheezing", "distress respiratory", "chronic obstructive airway disease"},
			{"sputum purulent", "distress respiratory", "wheezing", "chronic obstructive airway disease"},
			{"hallucinations auditory", "unresponsiveness", "agitation", "dementia"},
			{"hallucinations auditory", "agitation", "unresponsiveness", "dementia"},
			{"unresponsiveness", "hallucinations auditory", "agitation", "dementia"},
			{"unresponsiveness", "agitation", "hallucinations auditory", "dementia"},
			{"agitation", "hallucinations auditory", "unresponsiveness", "dementia"},
			{"agitation", "unresponsiveness", "hallucinations auditory", "dementia"}};

	//maps to get the required dataset
	static Map<String, String[][]> datas = Collections.unmodifiableMap(new HashMap<String, String[][]>() {
		private static final long serialVersionUID = 42L;

		{

			put("Diagnosis#1", Diagnosis);
			put("DIAGNOSIS#2", DIAGNOSIS);
		}
	});
}
